#!/usr/bin/env bash

set -euo pipefail

validator="$1"
fixture_root="$(mktemp -d)"

cleanup() {
	rm -rf -- "$fixture_root"
}
trap cleanup EXIT

fail() {
	echo "test failed: $1" >&2
	exit 1
}

new_source() {
	source_file="$fixture_root/$1.md"
	stdout="$fixture_root/$1.stdout"
	stderr="$fixture_root/$1.stderr"
}

expect_valid() {
	if ! python3 "$validator" "$source_file" >"$stdout" 2>"$stderr"; then
		cat "$stderr" >&2
		fail "$1 was rejected"
	fi
}

expect_invalid() {
	if python3 "$validator" "$source_file" >"$stdout" 2>"$stderr"; then
		fail "$1 was accepted"
	fi
	grep -F -- "$2" "$stderr" >/dev/null || fail "$1 returned the wrong diagnostic"
}

new_source canonical-links
printf '%s\n' \
	'# Canonical links' \
	'' \
	'[Web](https://example.invalid/path)' \
	'[Mail](mailto:operator@example.invalid)' >"$source_file"
expect_valid "canonical links"

new_source delimiter-aware-fences
printf '%s\n' \
	'````text' \
	'# Hidden one' \
	'~~~' \
	'# Hidden two' \
	'~~~' \
	'# Hidden three' \
	'```' \
	'# Hidden four' \
	'````' \
	'# Visible heading' \
	'' \
	'[Canonical](https://example.invalid)' >"$source_file"
expect_valid "delimiter-aware fences"

new_source indented-fence
printf '%s\n' \
	'   ~~~text' \
	'# Hidden heading' \
	'   ~~~~' \
	'# Visible heading' >"$source_file"
expect_valid "three-space-indented fence"

new_source visible-second-h1
printf '%s\n' \
	'# First heading' \
	'' \
	'## Detail' \
	'' \
	'# Second heading' >"$source_file"
expect_invalid "visible second H1" "exactly one H1 outside fenced code blocks"

new_source indented-second-h1
printf '%s\n' \
	'# First heading' \
	'' \
	'   # Indented second heading' >"$source_file"
expect_invalid "indented second H1" "exactly one H1 outside fenced code blocks"

new_source bare-second-h1
printf '%s\n' \
	'# First heading' \
	'' \
	'#' >"$source_file"
expect_invalid "bare second H1" "exactly one H1 outside fenced code blocks"

new_source setext-second-h1
printf '%s\n' \
	'# First heading' \
	'' \
	'Setext second heading' \
	'===' >"$source_file"
expect_invalid "Setext second H1" "exactly one H1 outside fenced code blocks"

new_source relative-reference
printf '%s\n' \
	'# Relative reference' \
	'' \
	'[Runbook][runbook]' \
	'' \
	'[runbook]: ../operations/runbook' >"$source_file"
expect_invalid "relative reference link" "unsupported Markdown reference link"

new_source raw-html-relative-link
printf '%s\n' \
	'# Raw HTML link' \
	'' \
	'<a href="../operations/runbook">Runbook</a>' >"$source_file"
expect_invalid "raw HTML relative link" "unsupported raw HTML link"

new_source multiline-raw-html-link
printf '%s\n' \
	'# Multiline raw HTML link' \
	'' \
	'<a' \
	'  href="../operations/runbook">Runbook</a>' >"$source_file"
expect_invalid "multiline raw HTML relative link" "unsupported raw HTML link"

new_source embedded-publisher-marker
printf '%s\n' \
	'# Embedded marker' \
	'' \
	'prefix <!-- generated by shulker server-docs; do not edit --> suffix' >"$source_file"
expect_invalid "embedded publisher marker" "publisher marker"

new_source relative-inline-link
printf '%s\n' \
	'# Relative inline link' \
	'' \
	'[Runbook](../operations/runbook)' >"$source_file"
expect_invalid "relative inline link" "canonical Markdown targets"
