#!/usr/bin/env bash

set -euo pipefail

sync_script="$1"
marker="<!-- generated by shulker server-docs; do not edit -->"
fixture_root="$(mktemp -d)"

cleanup() {
	rm -rf -- "$fixture_root"
}
trap cleanup EXIT

fail() {
	echo "test failed: $1" >&2
	exit 1
}

new_case() {
	case_dir="$fixture_root/$1"
	reports_dir="$case_dir/reports"
	wiki_dir="$case_dir/wiki"
	wiki_docs_dir="$case_dir/wiki-docs"
	mkdir -p "$reports_dir" "$wiki_dir" "$wiki_docs_dir"
	git -C "$wiki_dir" init -q
	printf '# Warden\n' >"$reports_dir/warden.md"
}

write_standard_pages() {
	printf '# Home\n' >"$wiki_docs_dir/Home.md"
	printf '# Services\n' >"$wiki_docs_dir/Services.md"
	printf 'Home.md\nServices.md\n' >"$wiki_docs_dir/wiki-pages.txt"
}

run_sync() {
	bash "$sync_script" "$reports_dir" "$wiki_dir" "$wiki_docs_dir" >"$case_dir/stdout" 2>"$case_dir/stderr"
}

expect_failure() {
	if run_sync; then
		fail "$1 unexpectedly succeeded"
	fi
}

expect_diagnostic() {
	grep -Fqx -- "$1" "$case_dir/stderr" || fail "missing diagnostic: $1"
}

new_case clean-manifest
write_standard_pages
run_sync
actual_pages="$(find "$wiki_dir" -maxdepth 1 -type f -name '*.md' -exec basename {} \; | sort)"
expected_pages=$'Home.md\nHost-warden.md\nServices.md'
[ "$actual_pages" = "$expected_pages" ] || fail "clean manifest page set"
for page in "$wiki_dir"/*.md; do
	[ "$(head -n 1 "$page")" = "$marker" ] || fail "managed page marker"
done

new_case unlisted-rogue
write_standard_pages
printf '# Rogue\n' >"$wiki_docs_dir/Rogue.md"
expect_failure "unlisted Rogue.md"
expect_diagnostic "Wiki page manifest does not match generated Markdown files"

new_case listed-missing-services
printf '# Home\n' >"$wiki_docs_dir/Home.md"
printf 'Home.md\nServices.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "missing Services.md"
expect_diagnostic "Wiki page manifest does not match generated Markdown files"

new_case duplicate-home
printf '# Home\n' >"$wiki_docs_dir/Home.md"
printf 'Home.md\nHome.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "duplicate Home.md"
expect_diagnostic "duplicate Wiki page name in manifest"

new_case escaped-name
printf '../Escape.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "../Escape.md"
expect_diagnostic "invalid Wiki page name in manifest"

new_case reserved-host-name
printf 'Host-shadow.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "Host-shadow.md"
expect_diagnostic "reserved Wiki page name in manifest"

new_case unmarked-collision
write_standard_pages
printf '# Manual Services\n' >"$wiki_dir/Services.md"
printf '%s\n\n# Old\n' "$marker" >"$wiki_dir/Old.md"
expect_failure "unmarked Services.md collision"
expect_diagnostic "refusing to overwrite manually maintained Wiki page: $wiki_dir/Services.md"
[ -f "$wiki_dir/Old.md" ] || fail "collision deleted stale marker-owned page"

new_case legacy-home
write_standard_pages
printf '%s\n%s\n' \
	'# Shulker infrastructure' \
	'Repository: [Conquerix/shulker](https://github.com/Conquerix/shulker)' >"$wiki_dir/Home.md"
run_sync
[ "$(head -n 1 "$wiki_dir/Home.md")" = "$marker" ] || fail "legacy Home.md was not replaced"

new_case unrelated-manual
write_standard_pages
printf '# Manual\n' >"$wiki_dir/Manual.md"
run_sync
[ "$(cat "$wiki_dir/Manual.md")" = '# Manual' ] || fail "unrelated Manual.md was changed"

new_case stale-marker-owned
write_standard_pages
printf '%s\n\n# Old\n' "$marker" >"$wiki_dir/Old.md"
run_sync
[ ! -e "$wiki_dir/Old.md" ] || fail "stale marker-owned Old.md was not removed"
