#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 9 ]; then
	echo "usage: $0 <sync-script> <host-docs> <wrong-name> <mismatched-report> <noncanonical-report> <chained-report> <escaping-report> <relative-report> <line-break-report>" >&2
	exit 2
fi

sync_script="$1"
real_host_docs="$2"
wrong_name_host_docs="$3"
mismatched_host_docs="$4"
noncanonical_host_docs="$5"
chained_host_docs="$6"
escaping_host_docs="$7"
relative_host_docs="$8"
line_break_host_docs="$9"
marker="<!-- generated by shulker server-docs; do not edit -->"
fixture_root="$(mktemp -d)"

cleanup() {
	rm -rf -- "$fixture_root"
}
trap cleanup EXIT

fail() {
	echo "test failed: $1" >&2
	exit 1
}

new_case() {
	case_dir="$fixture_root/$1"
	reports_dir="$case_dir/host-docs-result"
	wiki_dir="$case_dir/wiki"
	wiki_docs_dir="$case_dir/wiki-docs"
	mkdir -p "$wiki_dir" "$wiki_docs_dir"
	ln -s "$real_host_docs" "$reports_dir"
	git -C "$wiki_dir" init -q
}

write_standard_pages() {
	printf '# Home\n' >"$wiki_docs_dir/Home.md"
	printf '# Services\n' >"$wiki_docs_dir/Services.md"
	printf 'Home.md\nServices.md\n' >"$wiki_docs_dir/wiki-pages.txt"
}

replace_reports_dir() {
	if [ -L "$reports_dir" ]; then
		unlink "$reports_dir"
	elif [ -e "$reports_dir" ]; then
		rm -rf -- "$reports_dir"
	fi
}

use_reports_output() {
	replace_reports_dir
	ln -s "$1" "$reports_dir"
}

make_writable_reports_out_link() {
	replace_reports_dir
	generated_store="$case_dir/generated-store"
	generated_reports_dir="$generated_store/host-docs"
	mkdir -p "$generated_reports_dir"
	generated_report_dir="$generated_store/generated-warden.md"
	mkdir "$generated_report_dir"
	printf '# Warden\n' >"$generated_report_dir/warden.md"
	ln -s "$generated_report_dir/warden.md" "$generated_reports_dir/warden.md"
	ln -s "$generated_reports_dir" "$reports_dir"
}

run_sync_with_reports() {
	reports_argument="$1"
	(
		cd "$case_dir"
		bash "$sync_script" "$reports_argument" "$wiki_dir" "$wiki_docs_dir"
	) >"$case_dir/stdout" 2>"$case_dir/stderr"
}

run_sync() {
	run_sync_with_reports "$reports_dir"
}

expect_failure() {
	if run_sync; then
		fail "$1 unexpectedly succeeded"
	fi
}

expect_failure_with_reports() {
	reports_argument="$1"
	description="$2"
	if run_sync_with_reports "$reports_argument"; then
		fail "$description unexpectedly succeeded"
	fi
}

expect_success() {
	if ! run_sync; then
		cat "$case_dir/stderr" >&2
		fail "$1 unexpectedly failed"
	fi
}

expect_diagnostic() {
	grep -Fqx -- "$1" "$case_dir/stderr" || fail "missing diagnostic: $1"
}

new_case clean-manifest
write_standard_pages
expect_success "clean manifest"
find "$wiki_dir" -maxdepth 1 -type f -name '*.md' -exec basename {} \; | sort >"$case_dir/actual-pages"
{
	printf 'Home.md\nServices.md\n'
	for report in "$real_host_docs"/*.md; do
		printf 'Host-%s.md\n' "$(basename "$report" .md)"
	done
} | sort >"$case_dir/expected-pages"
[ "$(grep -c '^Host-' "$case_dir/expected-pages")" -eq 9 ] || fail "expected nine evaluated host reports"
cmp "$case_dir/expected-pages" "$case_dir/actual-pages" || fail "clean manifest page set"
for page in "$wiki_dir"/*.md; do
	[ "$(head -n 1 "$page")" = "$marker" ] || fail "managed page marker"
done

new_case generated-workflow-out-links
write_standard_pages
generated_output="$wiki_docs_dir"
wiki_docs_dir="$case_dir/wiki-docs-result"
ln -s "$generated_output" "$wiki_docs_dir"
expect_success "generated workflow out-links"
[ "$(head -n 1 "$wiki_dir/Home.md")" = "$marker" ] || fail "out-link Home.md marker"
[ "$(head -n 1 "$wiki_dir/Services.md")" = "$marker" ] || fail "out-link Services.md marker"
[ "$(head -n 1 "$wiki_dir/Host-warden.md")" = "$marker" ] || fail "out-link Host-warden.md marker"

new_case writable-generated-report-link-farm
write_standard_pages
make_writable_reports_out_link
expect_failure "writable generated report link farm"
expect_diagnostic "refusing unsafe generated reports out-link: $reports_dir"

new_case unlisted-rogue
write_standard_pages
printf '# Rogue\n' >"$wiki_docs_dir/Rogue.md"
expect_failure "unlisted Rogue.md"
expect_diagnostic "Wiki page manifest does not match generated Markdown files"

new_case listed-missing-services
printf '# Home\n' >"$wiki_docs_dir/Home.md"
printf 'Home.md\nServices.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "missing Services.md"
expect_diagnostic "Wiki page manifest does not match generated Markdown files"

new_case duplicate-home
printf '# Home\n' >"$wiki_docs_dir/Home.md"
printf 'Home.md\nHome.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "duplicate Home.md"
expect_diagnostic "duplicate Wiki page name in manifest"

new_case escaped-name
printf '../Escape.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "../Escape.md"
expect_diagnostic "invalid Wiki page name in manifest"

new_case reserved-host-name
printf 'Host-shadow.md\n' >"$wiki_docs_dir/wiki-pages.txt"
expect_failure "Host-shadow.md"
expect_diagnostic "reserved Wiki page name in manifest"

new_case unmarked-collision
write_standard_pages
printf '# Manual Services\n' >"$wiki_dir/Services.md"
printf '%s\n\n# Old\n' "$marker" >"$wiki_dir/Old.md"
expect_failure "unmarked Services.md collision"
expect_diagnostic "refusing to overwrite manually maintained Wiki page: $wiki_dir/Services.md"
[ -f "$wiki_dir/Old.md" ] || fail "collision deleted stale marker-owned page"

new_case legacy-home
write_standard_pages
printf '%s\n%s\n' \
	'# Shulker infrastructure' \
	'Repository: [Conquerix/shulker](https://github.com/Conquerix/shulker)' >"$wiki_dir/Home.md"
run_sync
[ "$(head -n 1 "$wiki_dir/Home.md")" = "$marker" ] || fail "legacy Home.md was not replaced"

new_case blank-separated-legacy-home
write_standard_pages
printf '%s\n\n%s\n' \
	'# Shulker infrastructure' \
	'Repository: [Conquerix/shulker](https://github.com/Conquerix/shulker)' >"$wiki_dir/Home.md"
expect_success "blank-separated legacy Home.md"
[ "$(head -n 1 "$wiki_dir/Home.md")" = "$marker" ] || fail "blank-separated legacy Home.md was not replaced"

new_case near-match-legacy-home
write_standard_pages
printf '%s\n\n%s\n' \
	'# Shulker infrastructure' \
	'Repository: [Conquerix/shulker](https://github.com/Conquerix/shulker/)' >"$wiki_dir/Home.md"
expect_failure "near-match legacy Home.md"
expect_diagnostic "refusing to overwrite manually maintained Wiki page: $wiki_dir/Home.md"

new_case unrelated-manual
write_standard_pages
printf '# Manual\n' >"$wiki_dir/Manual.md"
run_sync
[ "$(cat "$wiki_dir/Manual.md")" = '# Manual' ] || fail "unrelated Manual.md was changed"

new_case stale-marker-owned
write_standard_pages
printf '%s\n\n# Old\n' "$marker" >"$wiki_dir/Old.md"
run_sync
[ ! -e "$wiki_dir/Old.md" ] || fail "stale marker-owned Old.md was not removed"

new_case legacy-temp-symlink
write_standard_pages
printf '# Manual page\n' >"$wiki_dir/Manual.md"
cp "$wiki_dir/Manual.md" "$case_dir/Manual.before"
ln -s Manual.md "$wiki_dir/.Home.md.tmp"
expect_failure "legacy staging symlink"
expect_diagnostic "refusing legacy Wiki staging symlink: $wiki_dir/.Home.md.tmp"
cmp "$case_dir/Manual.before" "$wiki_dir/Manual.md" || fail "legacy staging symlink changed Manual.md"

new_case render-failure-preserves-wiki
write_standard_pages
printf '%s\n\n# Existing Home\n' "$marker" >"$wiki_dir/Home.md"
printf '%s\n\n# Existing Services\n' "$marker" >"$wiki_dir/Services.md"
printf '%s\n\n# Existing Warden\n' "$marker" >"$wiki_dir/Host-warden.md"
printf '%s\n\n# Stale\n' "$marker" >"$wiki_dir/Old.md"
printf '# Manual page\n' >"$wiki_dir/Manual.md"
mkdir "$case_dir/wiki-before"
cp "$wiki_dir"/*.md "$case_dir/wiki-before/"
chmod 000 "$wiki_docs_dir/Services.md"
expect_failure "unreadable Wiki source"
chmod 600 "$wiki_docs_dir/Services.md"
for page in Home.md Services.md Host-warden.md Old.md Manual.md; do
	cmp "$case_dir/wiki-before/$page" "$wiki_dir/$page" || fail "render failure changed $page"
done
if find "$wiki_dir" -maxdepth 1 -name '.shulker-wiki-stage.*' -print -quit | grep -q .; then
	fail "render failure left a staging directory"
fi

new_case destination-symlink
write_standard_pages
printf '%s\n\n# Outside\n' "$marker" >"$case_dir/outside.md"
cp "$case_dir/outside.md" "$case_dir/outside.before"
ln -s "$case_dir/outside.md" "$wiki_dir/Services.md"
expect_failure "destination symlink"
expect_diagnostic "refusing symlinked Wiki destination: $wiki_dir/Services.md"
cmp "$case_dir/outside.before" "$case_dir/outside.md" || fail "destination symlink target changed"

new_case report-symlink
write_standard_pages
replace_reports_dir
mkdir "$reports_dir"
printf '# External report\n' >"$case_dir/external-report.md"
ln -s "$case_dir/external-report.md" "$reports_dir/warden.md"
expect_failure "report symlink"
expect_diagnostic "refusing unsafe generated reports out-link: $reports_dir"

new_case relative-reports-caller
write_standard_pages
expect_failure_with_reports "host-docs-result" "relative generated reports caller"
expect_diagnostic "refusing unsafe generated reports out-link: host-docs-result"

new_case chained-reports-out-link
write_standard_pages
mv "$reports_dir" "$case_dir/host-docs-alias"
ln -s "$case_dir/host-docs-alias" "$reports_dir"
expect_failure "chained generated reports out-link"
expect_diagnostic "refusing unsafe generated reports out-link: $reports_dir"

new_case dotdot-reports-out-link
write_standard_pages
replace_reports_dir
ln -s "/nix/store/../store/$(basename "$real_host_docs")" "$reports_dir"
expect_failure "noncanonical generated reports out-link"
expect_diagnostic "refusing unsafe generated reports out-link: $reports_dir"

new_case wrong-output-name
write_standard_pages
use_reports_output "$wrong_name_host_docs"
expect_failure "wrong generated reports output name"
expect_diagnostic "refusing unsafe generated reports out-link: $reports_dir"

new_case mismatched-generated-report
write_standard_pages
use_reports_output "$mismatched_host_docs"
expect_failure "generated report basename mismatch"
expect_diagnostic "refusing symlinked host report: $reports_dir/warden.md"

new_case chained-generated-report
write_standard_pages
use_reports_output "$chained_host_docs"
expect_failure "generated report symlink chain"
expect_diagnostic "refusing symlinked host report: $reports_dir/warden.md"

new_case noncanonical-generated-report
write_standard_pages
use_reports_output "$noncanonical_host_docs"
expect_failure "noncanonical generated report target"
expect_diagnostic "refusing symlinked host report: $reports_dir/warden.md"

new_case generated-report-link-escape
write_standard_pages
use_reports_output "$escaping_host_docs"
expect_failure "generated report link escaping trusted root"
expect_diagnostic "refusing symlinked host report: $reports_dir/warden.md"

new_case generated-report-relative-link
write_standard_pages
use_reports_output "$relative_host_docs"
expect_failure "relative generated report link"
expect_diagnostic "refusing symlinked host report: $reports_dir/warden.md"

new_case generated-report-line-break-link
write_standard_pages
use_reports_output "$line_break_host_docs"
expect_failure "line-break generated report link"
expect_diagnostic "refusing symlinked host report: $reports_dir/warden.md"
