# Auto-generated by compose2nix.

{
  lib,
  config,
  ...
}:
let
  cfg = config.shulker.system.modules.newt;
in
with lib;
{
  options.shulker.system.modules.newt = {
    enable = lib.mkEnableOption "Enable newt";
    impermanence = mkEnableOption "Enable impermanence.";
    endpoint = mkOption {
      type = types.str;
      default = "example.com";
      description = "Url where pangolin is accessible.";
    };
    stateDir = mkOption {
      type = types.str;
      default = "/var/lib/newt";
      description = "State Directory.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.newt = {
      enable = true;
      settings.endpoint = cfg.endpoint;
      environmentFile = config.services.onepassword-secrets.secrets.newtEnv.path;
    };

    environment.persistence = mkIf (cfg.impermanence) {
      "/nix/persist".directories = [
        {
          directory = "${cfg.stateDir}";
          mode = "u=rwx,g=rx,o=rx";
        }
      ];
    };

    systemd.services.newt.serviceConfig.DynamicUser = mkForce false;
    systemd.services.newt.environment.HOME = mkForce cfg.stateDir;

    services.onepassword-secrets.secrets.newtEnv = {
      reference = "op://Shulker/${config.networking.hostName}/Newt env";
      services = [ "newt" ];
    };
  };
}
