# Auto-generated by compose2nix.

{
  lib,
  config,
  ...
}:
let
  cfg = config.shulker.system.modules.newt;
in
with lib;
{
  options.shulker.system.modules.newt = {
    enable = lib.mkEnableOption "Enable newt";
    endpoint = mkOption {
      type = types.str;
      default = "example.com";
      description = "Url where pangolin is accessible.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.newt = {
      enable = true;
      settings.endpoint = cfg.endpoint;
      environmentFile = config.services.onepassword-secrets.secrets.newtEnv.path;
    };

    services.onepassword-secrets.secrets.newtEnv = {
      reference = "op://Shulker/${config.networking.hostName}/Newt env";
      services = [ "newt" ];
      # owner = "newt";
      # group = "newt";
    };
  };
}
