{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.shulker.system.modules.nextcloud;
in
{
  options.shulker.system.modules.nextcloud = {
    enable = mkEnableOption "Enable nextcloud service.";
    impermanence = mkEnableOption "Enable impermanence.";
    baseUrl = mkOption {
      type = types.str;
      default = "example.com";
      description = "Default url where nextcloud will be accessible.";
    };
    mainSubDomain = mkOption {
      type = types.str;
      default = "nextcloud";
      description = "Default subdomain where nextcloud will be accessible.";
    };
    aioSubDomain = mkOption {
      type = types.str;
      default = "nextcloud-aio";
      description = "Default subdomain where nextcloud aio will be accessible.";
    };
    mainPort = mkOption {
      type = types.port;
      default = 8080;
      description = "Default internal port to open nextcloud.";
    };
    aioPort = mkOption {
      type = types.port;
      default = 8081;
      description = "Default internal port to open nextcloud aio.";
    };
  };

  config = mkIf cfg.enable {

    # Containers
    virtualisation.oci-containers.containers."nextcloud-aio-mastercontainer" = {
      image = "ghcr.io/nextcloud-releases/all-in-one:latest";
      environment = {
        "APACHE_IP_BINDING" = "127.0.0.1";
        "APACHE_PORT" = "${toString cfg.mainPort}";
        "SKIP_DOMAIN_VALIDATION" = "false";
      };
      volumes = [
        "/var/run/docker.sock:/var/run/docker.sock:ro"
        "nextcloud_aio_mastercontainer:/mnt/docker-aio-config:rw"
      ];
      ports = [
        "127.0.0.1:${toString cfg.aioPort}:8080/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=nextcloud-aio-mastercontainer"
        "--network=nextcloud-aio"
      ];
    };
    systemd.services."docker-nextcloud-aio-mastercontainer" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-nextcloud-aio.service"
        "docker-volume-nextcloud_aio_mastercontainer.service"
      ];
      requires = [
        "docker-network-nextcloud-aio.service"
        "docker-volume-nextcloud_aio_mastercontainer.service"
      ];
      partOf = [
        "docker-compose-nextcloud-aio-root.target"
      ];
      wantedBy = [
        "docker-compose-nextcloud-aio-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-nextcloud-aio" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f nextcloud-aio";
      };
      script = ''
        docker network inspect nextcloud-aio || docker network create nextcloud-aio --opt=com.docker.network.driver.mtu=1440
      '';
      partOf = [ "docker-compose-nextcloud-aio-root.target" ];
      wantedBy = [ "docker-compose-nextcloud-aio-root.target" ];
    };

    # Volumes
    systemd.services."docker-volume-nextcloud_aio_mastercontainer" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        docker volume inspect nextcloud_aio_mastercontainer || docker volume create nextcloud_aio_mastercontainer
      '';
      partOf = [ "docker-compose-nextcloud-aio-root.target" ];
      wantedBy = [ "docker-compose-nextcloud-aio-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-nextcloud-aio-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    services.nginx = {
      enable = true;
      virtualHosts."nextcloud" = {
        serverName = "${cfg.mainSubDomain}.${cfg.baseUrl}";
        forceSSL = true;
        useACMEHost = cfg.baseUrl;
        locations."/" = {
          proxyWebsockets = true;
          proxyPass = "http://127.0.0.1:${toString cfg.mainPort}";
        };
      };
      virtualHosts."nextcloud-aio" = {
        serverName = "${cfg.aioSubDomain}.${cfg.baseUrl}";
        forceSSL = true;
        useACMEHost = cfg.baseUrl;
        locations."/" = {
          proxyWebsockets = true;
          proxyPass = "https://127.0.0.1:${toString cfg.aioPort}";
        };
      };
    };
  };
}
