# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:
let
  cfg = config.shulker.system.modules.pangolin;
in
with lib;
{
  options.shulker.system.modules.pangolin = {
    enable = lib.mkEnableOption "Enable pangolin";
    impermanence = mkEnableOption "Enable impermanence.";
    stateDir = mkOption {
      type = types.str;
      default = "/var/lib/pangolin";
      description = "State Directory.";
    };
  };

  config = lib.mkIf cfg.enable {

    # Gerbil container
    virtualisation.oci-containers.containers."gerbil" = {
      image = "docker.io/fosrl/gerbil:latest";
      volumes = [ "${cfg.stateDir}/config:/var/config:rw" ];
      ports = [
        "51820:51820/udp"
        "21820:21820/udp"
        "443:443/tcp"
        "80:80/tcp"
      ];
      cmd = [
        "--reachableAt=http://gerbil:3004"
        "--generateAndSaveKeyTo=/var/config/key"
        "--remoteConfig=http://pangolin:3001/api/v1/"
      ];
      dependsOn = [ "pangolin" ];
      log-driver = "journald";
      extraOptions = [
        "--cap-add=NET_ADMIN"
        "--cap-add=SYS_MODULE"
        "--network-alias=gerbil"
        "--network=pangolin"
      ];
    };
    systemd.services."docker-gerbil" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [ "docker-network-pangolin.service" ];
      requires = [ "docker-network-pangolin.service" ];
      partOf = [ "docker-compose-pangolin-root.target" ];
      wantedBy = [ "docker-compose-pangolin-root.target" ];
    };

    # Pangolin container
    virtualisation.oci-containers.containers."pangolin" = {
      image = "docker.io/fosrl/pangolin:ee-latest";
      volumes = [ "${cfg.stateDir}/config:/app/config:rw" ];
      log-driver = "journald";
      extraOptions = [
        ''--health-cmd=["/usr/bin/curl", "-f", "http://localhost:3001/api/v1/"]''
        "--health-interval=10s"
        "--health-retries=15"
        "--health-timeout=10s"
        "--network-alias=pangolin"
        "--network=pangolin"
      ];
    };
    systemd.services."docker-pangolin" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [ "docker-network-pangolin.service" ];
      requires = [ "docker-network-pangolin.service" ];
      partOf = [ "docker-compose-pangolin-root.target" ];
      wantedBy = [ "docker-compose-pangolin-root.target" ];
    };

    # Traefik container
    virtualisation.oci-containers.containers."traefik" = {
      image = "docker.io/traefik:v3.6";
      volumes = [
        "${cfg.stateDir}/config/letsencrypt:/letsencrypt:rw"
        "${cfg.stateDir}/config/traefik:/etc/traefik:ro"
        "${cfg.stateDir}/config/traefik/logs:/var/log/traefik:rw"
      ];
      cmd = [ "--configFile=/etc/traefik/traefik_config.yml" ];
      dependsOn = [
        "gerbil"
        "pangolin"
      ];
      log-driver = "journald";
      extraOptions = [ "--network=container:gerbil" ];
    };
    systemd.services."docker-traefik" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      partOf = [ "docker-compose-pangolin-root.target" ];
      wantedBy = [ "docker-compose-pangolin-root.target" ];
    };

    # Pangolin network
    systemd.services."docker-network-pangolin" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f pangolin";
      };
      script = "docker network inspect pangolin || docker network create pangolin --driver=bridge";
      partOf = [ "docker-compose-pangolin-root.target" ];
      wantedBy = [ "docker-compose-pangolin-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-pangolin-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    environment.persistence = mkIf cfg.impermanence {
      "/nix/persist".directories = [
        {
          directory = "${cfg.stateDir}";
          mode = "u=rwx,g=rx,o=rx";
        }
      ];
    };

    shulker.system.modules.backup.dirs = [ cfg.stateDir ];
    services.borgmatic.settings.sqlite_databases = [
      {
        name = "pelican-panel-db";
        path = "${cfg.stateDir}/config/db/db.sqlite";
      }
    ];
  };
}
