#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
	echo "usage: $0 <generated-reports-directory> <wiki-checkout>" >&2
	exit 2
fi

reports_dir="$1"
wiki_dir="$2"
marker="<!-- generated by shulker server-docs; do not edit -->"
index_page="$wiki_dir/Servers.md"

if [ ! -d "$reports_dir" ]; then
	echo "reports directory does not exist: $reports_dir" >&2
	exit 1
fi

if [ ! -d "$wiki_dir/.git" ]; then
	echo "Wiki checkout is not a Git repository: $wiki_dir" >&2
	exit 1
fi

assert_managed_or_absent() {
	page="$1"
	if [ -e "$page" ] && ! grep -Fqx "$marker" "$page"; then
		echo "refusing to overwrite manually maintained Wiki page: $page" >&2
		exit 1
	fi
}

assert_managed_or_absent "$index_page"

report_count=0
for report in "$reports_dir"/*.md; do
	if [ ! -e "$report" ]; then
		continue
	fi

	report_count=$((report_count + 1))
	host="$(basename "$report" .md)"
	assert_managed_or_absent "$wiki_dir/Server-$host.md"
done

if [ "$report_count" -eq 0 ]; then
	echo "no Markdown reports found in: $reports_dir" >&2
	exit 1
fi

# Remove only pages carrying our marker, so stale generated hosts disappear
# without touching unrelated or manually maintained Wiki content.
for page in "$wiki_dir"/Server-*.md; do
	if [ -e "$page" ] && grep -Fqx "$marker" "$page"; then
		rm -f -- "$page"
	fi
done

index_tmp="$wiki_dir/.Servers.md.tmp"
{
	echo "$marker"
	echo
	echo "# Servers"
	echo
	echo "These reports are generated from the evaluated NixOS configurations."
	echo
	for report in "$reports_dir"/*.md; do
		host="$(basename "$report" .md)"
		echo "- [$host](Server-$host)"
	done
} >"$index_tmp"
mv -- "$index_tmp" "$index_page"

for report in "$reports_dir"/*.md; do
	host="$(basename "$report" .md)"
	page="$wiki_dir/Server-$host.md"
	page_tmp="$wiki_dir/.Server-$host.md.tmp"
	{
		echo "$marker"
		echo
		sed "1s/^# /# Server: /" "$report"
	} >"$page_tmp"
	mv -- "$page_tmp" "$page"
done
