#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 3 ]; then
	echo "usage: $0 <generated-reports-directory> <wiki-checkout> <generated-wiki-directory>" >&2
	exit 2
fi

reports_dir="$1"
wiki_dir="$2"
wiki_docs_dir="$3"
marker="<!-- generated by shulker server-docs; do not edit -->"

if [ ! -d "$reports_dir" ]; then
	echo "reports directory does not exist: $reports_dir" >&2
	exit 1
fi

if [ ! -d "$wiki_dir/.git" ]; then
	echo "Wiki checkout is not a Git repository: $wiki_dir" >&2
	exit 1
fi

if [ ! -d "$wiki_docs_dir" ]; then
	echo "generated Wiki directory does not exist: $wiki_docs_dir" >&2
	exit 1
fi

assert_managed_or_absent() {
	page="$1"
	if [ ! -e "$page" ] || grep -Fqx "$marker" "$page"; then
		return
	fi

	if [ "$(basename "$page")" = "Home.md" ] &&
		grep -Fqx "# Shulker infrastructure" "$page" &&
		grep -Fqx "Repository: [Conquerix/shulker](https://github.com/Conquerix/shulker)" "$page"; then
		return
	fi

	if [ -e "$page" ]; then
		echo "refusing to overwrite manually maintained Wiki page: $page" >&2
		exit 1
	fi
}

for required_page in Home Fleet Servers Services Public-Services Infrastructure Operations Automation _Sidebar _Footer; do
	if [ ! -f "$wiki_docs_dir/$required_page.md" ]; then
		echo "required generated Wiki page does not exist: $wiki_docs_dir/$required_page.md" >&2
		exit 1
	fi
done

wiki_doc_count=0
for source_page in "$wiki_docs_dir"/*.md; do
	if [ ! -e "$source_page" ]; then
		continue
	fi

	wiki_doc_count=$((wiki_doc_count + 1))
	assert_managed_or_absent "$wiki_dir/$(basename "$source_page")"
done

if [ "$wiki_doc_count" -eq 0 ]; then
	echo "no generated Wiki pages found in: $wiki_docs_dir" >&2
	exit 1
fi

report_count=0
for report in "$reports_dir"/*.md; do
	if [ ! -e "$report" ]; then
		continue
	fi

	report_count=$((report_count + 1))
	host="$(basename "$report" .md)"
	assert_managed_or_absent "$wiki_dir/Host-$host.md"
done

if [ "$report_count" -eq 0 ]; then
	echo "no Markdown reports found in: $reports_dir" >&2
	exit 1
fi

# Remove only pages carrying our marker. This clears stale generated pages and
# hosts without touching unrelated or manually maintained Wiki content.
for page in "$wiki_dir"/*.md; do
	if [ -e "$page" ] && grep -Fqx "$marker" "$page"; then
		rm -f -- "$page"
	fi
done

for source_page in "$wiki_docs_dir"/*.md; do
	page_name="$(basename "$source_page")"
	page="$wiki_dir/$page_name"
	page_tmp="$wiki_dir/.$page_name.tmp"
	{
		echo "$marker"
		echo
		cat "$source_page"
	} >"$page_tmp"
	mv -- "$page_tmp" "$page"
done

for report in "$reports_dir"/*.md; do
	host="$(basename "$report" .md)"
	page="$wiki_dir/Host-$host.md"
	page_tmp="$wiki_dir/.Host-$host.md.tmp"
	{
		echo "$marker"
		echo
		echo "[← Fleet](Fleet) · [Servers](Servers) · [Services](Services) · [Operations](Operations)"
		echo
		sed "1s/^# /# Host: /" "$report"
	} >"$page_tmp"
	mv -- "$page_tmp" "$page"
done
