#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 3 ]; then
	echo "usage: $0 <generated-reports-directory> <wiki-checkout> <generated-wiki-directory>" >&2
	exit 2
fi

reports_dir="$1"
wiki_dir="$2"
wiki_docs_dir="$3"
marker="<!-- generated by shulker server-docs; do not edit -->"

if [ ! -d "$reports_dir" ]; then
	echo "reports directory does not exist: $reports_dir" >&2
	exit 1
fi

if [ ! -d "$wiki_dir/.git" ]; then
	echo "Wiki checkout is not a Git repository: $wiki_dir" >&2
	exit 1
fi

if [ ! -d "$wiki_docs_dir" ]; then
	echo "generated Wiki directory does not exist: $wiki_docs_dir" >&2
	exit 1
fi

manifest="$wiki_docs_dir/wiki-pages.txt"
if [ -L "$manifest" ]; then
	echo "refusing symlinked Wiki page manifest: $manifest" >&2
	exit 1
fi
if [ ! -f "$manifest" ] || [ ! -s "$manifest" ]; then
	echo "Wiki page manifest does not exist" >&2
	exit 1
fi

manifest_names="$(mktemp)"
markdown_names="$(mktemp)"
comparison_names="$(mktemp)"
staging_dir=""
cleanup() {
	rm -f -- "$manifest_names" "$markdown_names" "$comparison_names"
	if [ -n "$staging_dir" ] && [ -d "$staging_dir" ]; then
		rm -rf -- "$staging_dir"
	fi
}
trap cleanup EXIT

while IFS= read -r page_name || [ -n "$page_name" ]; do
	case "$page_name" in
	Host-*)
		echo "reserved Wiki page name in manifest" >&2
		exit 1
		;;
	esac

	if [[ ! $page_name =~ ^(_Sidebar|_Footer|[A-Za-z0-9][A-Za-z0-9-]*)[.]md$ ]]; then
		echo "invalid Wiki page name in manifest" >&2
		exit 1
	fi

	if [ -L "$wiki_docs_dir/$page_name" ]; then
		echo "refusing symlinked generated Wiki page: $wiki_docs_dir/$page_name" >&2
		exit 1
	fi

	if [ ! -f "$wiki_docs_dir/$page_name" ]; then
		echo "Wiki page manifest does not match generated Markdown files" >&2
		exit 1
	fi

	printf '%s\n' "$page_name" >>"$manifest_names"
done <"$manifest"

if sort "$manifest_names" | uniq -d | grep -q .; then
	echo "duplicate Wiki page name in manifest" >&2
	exit 1
fi

sort "$manifest_names" -o "$manifest_names"
find -H "$wiki_docs_dir" -maxdepth 1 -type f -name '*.md' -exec basename {} \; | sort >"$markdown_names"
comm -3 "$manifest_names" "$markdown_names" >"$comparison_names"
if [ -s "$comparison_names" ]; then
	echo "Wiki page manifest does not match generated Markdown files" >&2
	exit 1
fi

assert_managed_or_absent() {
	page="$1"
	if [ -L "$page" ]; then
		echo "refusing symlinked Wiki destination: $page" >&2
		exit 1
	fi

	if [ ! -e "$page" ] || grep -Fqx "$marker" "$page"; then
		return
	fi

	if [ "$(basename "$page")" = "Home.md" ] &&
		grep -Fqx "# Shulker infrastructure" "$page" &&
		grep -Fqx "Repository: [Conquerix/shulker](https://github.com/Conquerix/shulker)" "$page"; then
		return
	fi

	if [ -e "$page" ]; then
		echo "refusing to overwrite manually maintained Wiki page: $page" >&2
		exit 1
	fi
}

assert_no_legacy_staging_symlink() {
	page="$1"
	legacy_staging="$wiki_dir/.$(basename "$page").tmp"
	if [ -L "$legacy_staging" ]; then
		echo "refusing legacy Wiki staging symlink: $legacy_staging" >&2
		exit 1
	fi
}

while IFS= read -r page_name; do
	assert_managed_or_absent "$wiki_dir/$page_name"
	assert_no_legacy_staging_symlink "$wiki_dir/$page_name"
done <"$manifest_names"

report_count=0
for report in "$reports_dir"/*.md; do
	if [ -L "$report" ]; then
		echo "refusing symlinked host report: $report" >&2
		exit 1
	fi

	if [ ! -e "$report" ]; then
		continue
	fi

	report_count=$((report_count + 1))
	host="$(basename "$report" .md)"
	if [[ ! $host =~ ^[A-Za-z0-9][A-Za-z0-9-]*$ ]]; then
		echo "invalid host report name: $report" >&2
		exit 1
	fi
	assert_managed_or_absent "$wiki_dir/Host-$host.md"
	assert_no_legacy_staging_symlink "$wiki_dir/Host-$host.md"
done

if [ "$report_count" -eq 0 ]; then
	echo "no Markdown reports found in: $reports_dir" >&2
	exit 1
fi

staging_dir="$(mktemp -d "$wiki_dir/.shulker-wiki-stage.XXXXXX")"
chmod 700 "$staging_dir"

while IFS= read -r page_name; do
	source_page="$wiki_docs_dir/$page_name"
	staged_page="$staging_dir/$page_name"
	{
		echo "$marker"
		echo
		cat "$source_page"
	} >"$staged_page"
done <"$manifest_names"

for report in "$reports_dir"/*.md; do
	host="$(basename "$report" .md)"
	staged_page="$staging_dir/Host-$host.md"
	{
		echo "$marker"
		echo
		echo "[← Fleet](Fleet) · [Servers](Servers) · [Services](Services) · [Operations](Operations)"
		echo
		sed "1s/^# /# Host: /" "$report"
	} >"$staged_page"
done

# Recheck all expected destinations after rendering and before any mutation.
while IFS= read -r page_name; do
	assert_managed_or_absent "$wiki_dir/$page_name"
done <"$manifest_names"
for report in "$reports_dir"/*.md; do
	host="$(basename "$report" .md)"
	assert_managed_or_absent "$wiki_dir/Host-$host.md"
done

# Refuse every Markdown symlink before removing any stale marker-owned page.
for page in "$wiki_dir"/*.md; do
	if [ -L "$page" ]; then
		echo "refusing symlinked Wiki destination: $page" >&2
		exit 1
	fi
done

# Remove only pages carrying our marker. Rendering has already completed, so a
# source failure cannot remove or partially replace existing Wiki content.
for page in "$wiki_dir"/*.md; do
	if [ -f "$page" ] && grep -Fqx "$marker" "$page"; then
		rm -f -- "$page"
	fi
done

while IFS= read -r page_name; do
	staged_page="$staging_dir/$page_name"
	if [ -L "$staged_page" ] || [ ! -f "$staged_page" ]; then
		echo "staged Wiki page is not a regular file: $staged_page" >&2
		exit 1
	fi
	mv -- "$staged_page" "$wiki_dir/$page_name"
done <"$manifest_names"

for report in "$reports_dir"/*.md; do
	host="$(basename "$report" .md)"
	staged_page="$staging_dir/Host-$host.md"
	if [ -L "$staged_page" ] || [ ! -f "$staged_page" ]; then
		echo "staged host page is not a regular file: $staged_page" >&2
		exit 1
	fi
	mv -- "$staged_page" "$wiki_dir/Host-$host.md"
done
