#!/usr/bin/env python3

import re
import sys
from pathlib import Path


PUBLISHER_MARKER = "<!-- generated by shulker server-docs; do not edit -->"
ABSOLUTE_URI = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")
OPENING_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")
ATX_H1 = re.compile(r"^ {0,3}#(?:[ \t]+.*)?[ \t]*$")
SETEXT_H1 = re.compile(r"^ {0,3}=+[ \t]*$")
INLINE_LINK = re.compile(r"\]\(([^)\n]*)\)")
REFERENCE_DEFINITION = re.compile(r"^ {0,3}\[[^]\n]+\]:")
REFERENCE_LINK = re.compile(r"!?\[[^]\n]+\]\[[^]\n]*\]")
RAW_HTML_LINK = re.compile(
    r"<\s*(?:a|area|audio|iframe|img|link|script|source|video)\b",
    re.IGNORECASE,
)


def fail(path: Path, message: str) -> None:
    print(f"{path}: {message}", file=sys.stderr)
    raise SystemExit(1)


def canonical_target(raw_target: str) -> bool:
    raw_target = raw_target.strip()
    if raw_target.startswith("<"):
        closing_angle = raw_target.find(">")
        if closing_angle == -1:
            return False
        target = raw_target[1:closing_angle]
    else:
        target = raw_target.split(maxsplit=1)[0] if raw_target else ""

    return bool(ABSOLUTE_URI.match(target))


def validate_links(path: Path, line: str) -> None:
    if REFERENCE_DEFINITION.match(line) or REFERENCE_LINK.search(line):
        fail(path, "unsupported Markdown reference link")

    if RAW_HTML_LINK.search(line):
        fail(path, "unsupported raw HTML link")

    for match in INLINE_LINK.finditer(line):
        if not canonical_target(match.group(1)):
            fail(path, "canonical Markdown targets")

    if "](" in INLINE_LINK.sub("", line):
        fail(path, "unsupported Markdown inline link")


def validate(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    if PUBLISHER_MARKER in text:
        fail(path, "publisher marker")

    fence_character = None
    fence_length = 0
    headings = 0
    previous_line = ""
    for line in lines:
        if fence_character is not None:
            closing_fence = re.compile(
                rf"^ {{0,3}}{re.escape(fence_character)}{{{fence_length},}}[ \t]*$"
            )
            if closing_fence.match(line):
                fence_character = None
                fence_length = 0
                previous_line = ""
            continue

        opening_fence = OPENING_FENCE.match(line)
        if opening_fence is not None:
            fence = opening_fence.group(1)
            info = opening_fence.group(2)
            if fence[0] == "`" and "`" in info:
                fail(path, "invalid backtick fence info string")
            fence_character = fence[0]
            fence_length = len(fence)
            previous_line = ""
            continue

        if ATX_H1.match(line) or (SETEXT_H1.match(line) and previous_line.strip()):
            headings += 1

        validate_links(path, line)
        previous_line = line

    if headings != 1:
        fail(path, "exactly one H1 outside fenced code blocks")


def main() -> None:
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <Markdown-source>", file=sys.stderr)
        raise SystemExit(2)

    validate(Path(sys.argv[1]))


if __name__ == "__main__":
    main()
