{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.shulker.system.modules.seafile;
  maintenanceLock = "/run/lock/seafile-maintenance.lock";
  pythonCommand = "/opt/seafile/seafile-server-latest/seahub.sh python-env python -";
  expectedServices = [
    "database"
    "metadata"
    "notification"
    "onlyoffice"
    "redis"
    "seafile"
    "seasearch"
  ];
  expectedContainers = {
    database = "seafile-mariadb";
    metadata = "seafile-metadata";
    notification = "seafile-notification";
    onlyoffice = "seafile-onlyoffice";
    redis = "seafile-redis";
    seafile = "seafile";
    seasearch = "seafile-seasearch";
  };
  commandPrelude = ''
    # shellcheck disable=SC1090,SC2034
    systemctl_command="''${SEAFILE_SYSTEMCTL_COMMAND:-systemctl}"
    docker_command="''${SEAFILE_DOCKER_COMMAND:-docker}"
    curl_command="''${SEAFILE_CURL_COMMAND:-curl}"
    flock_command="''${SEAFILE_FLOCK_COMMAND:-flock}"
    id_command="''${SEAFILE_ID_COMMAND:-id}"
    state_dir="''${SEAFILE_STATE_DIR:-${cfg.stateDir}}"
    host_dir="''${SEAFILE_HOST_DIR:-/run/seafile-host}"
    app_dir="''${SEAFILE_APP_DIR:-/run/seafile-app}"
    metadata_dir="''${SEAFILE_METADATA_DIR:-/run/seafile-metadata}"
    lock_file="''${SEAFILE_MAINTENANCE_LOCK:-${maintenanceLock}}"
    environment_file="$host_dir/environment"
    : "$systemctl_command" "$docker_command" "$curl_command" "$flock_command" \
      "$id_command" "$state_dir" "$host_dir" "$app_dir" "$metadata_dir" "$lock_file" "$environment_file"

    fail_maintenance() {
      echo "Seafile $1 probe failed" >&2
      exit 69
    }

    prove_inherited_lock() {
      local fd_path fd_identity lock_identity
      if [ -e /proc/self/fd/9 ]; then
        fd_path=/proc/self/fd/9
        fd_identity="$(stat --dereference --format '%d:%i' -- "$fd_path" 2>/dev/null)" \
          || { echo "Seafile inherited maintenance lock descriptor is invalid" >&2; exit 77; }
        lock_identity="$(stat --format '%d:%i' -- "$lock_file" 2>/dev/null)" \
          || { echo "Seafile maintenance lock path is invalid" >&2; exit 77; }
      elif [ -e /dev/fd/9 ]; then
        fd_path=/dev/fd/9
        # Darwin's fdesc filesystem reports a synthetic device number while
        # preserving the target inode. Production NixOS uses the /proc branch.
        fd_identity="$(stat --dereference --format '%i' -- "$fd_path" 2>/dev/null)" \
          || { echo "Seafile inherited maintenance lock descriptor is invalid" >&2; exit 77; }
        lock_identity="$(stat --format '%i' -- "$lock_file" 2>/dev/null)" \
          || { echo "Seafile maintenance lock path is invalid" >&2; exit 77; }
      else
        echo "Seafile inherited maintenance lock descriptor is missing" >&2
        exit 77
      fi
      [ "$fd_identity" = "$lock_identity" ] \
        || { echo "Seafile inherited descriptor does not identify the maintenance lock" >&2; exit 77; }
      exec 8>"$lock_file"
      if "$flock_command" -n 8; then
        "$flock_command" -u 8
        exec 8>&-
        echo "Seafile inherited maintenance lock descriptor is not held" >&2
        exit 77
          fi
          exec 8>&-
          "$flock_command" -n 9 \
            || { echo "Seafile inherited maintenance lock descriptor is not held" >&2; exit 77; }
        }

    load_runtime_environment() {
      [ -f "$environment_file" ] && [ ! -L "$environment_file" ] \
        || fail_maintenance "runtime environment"
      [ "$(stat --format '%a' -- "$environment_file")" = 400 ] \
        || fail_maintenance "runtime environment"
      set -a
      # The file is generated by seafile-parse-environment from a strict
      # key/value allow-list whose values contain no shell syntax.
      # shellcheck disable=SC1090
      . "$environment_file"
      set +a
    }
  '';
  healthCheckScript = ''
        ${commandPrelude}

        if [ "''${SEAFILE_MAINTENANCE_LOCK_HELD:-0}" = 1 ]; then
          prove_inherited_lock
        else
          exec 9>"$lock_file"
          if ! "$flock_command" -n 9; then
            echo "Seafile maintenance in progress"
            exit 0
          fi
        fi

        if ! "$systemctl_command" is-active --quiet seafile-compose.service; then
          echo "Seafile Compose service is not active" >&2
          exit 69
        fi

        actual_services="$({
          "$docker_command" ps \
            --filter label=com.docker.compose.project=seafile \
            --format '{{.Label "com.docker.compose.service"}}'
        } | sort)"
        expected_services="$(printf '%s\n' ${lib.concatStringsSep " " expectedServices} | sort)"
        if [ "$actual_services" != "$expected_services" ]; then
          echo "Seafile does not have exactly seven running Compose services" >&2
          exit 69
        fi

        ${lib.concatMapStringsSep "\n" (service: ''
          if [ "$("$docker_command" inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}' ${
            lib.escapeShellArg expectedContainers.${service}
          } 2>/dev/null)" != healthy ]; then
            echo "Seafile ${service} container health probe failed" >&2
            exit 69
          fi
        '') expectedServices}

        if ! "$curl_command" --fail --silent --show-error --max-time 10 \
          http://${cfg.bindAddress}:${toString cfg.port}/ >/dev/null; then
          fail_maintenance "HTTP"
        fi
        if ! "$curl_command" --fail --silent --show-error --max-time 10 \
          http://${cfg.bindAddress}:${toString cfg.notificationPort}/ping >/dev/null; then
          fail_maintenance "Notification"
        fi
        onlyoffice_health="$({
          "$curl_command" --fail --silent --show-error --max-time 10 \
            http://${cfg.bindAddress}:${toString cfg.onlyOfficePort}/healthcheck
        } 2>/dev/null)" || fail_maintenance "OnlyOffice"
        [ "$onlyoffice_health" = true ] || fail_maintenance "OnlyOffice"

        load_runtime_environment

        export MYSQL_PWD="$SEAFILE_MYSQL_DB_PASSWORD"
        sql_result="$({
          "$docker_command" exec --env MYSQL_PWD seafile-mariadb \
            mariadb --batch --skip-column-names --user seafile seafile_db \
            --execute 'SELECT 1'
        } 2>/dev/null)" || fail_maintenance "SQL"
        unset MYSQL_PWD
        [ "$sql_result" = 1 ] || fail_maintenance "SQL"

        export REDISCLI_AUTH="$REDIS_PASSWORD"
        redis_result="$({
          "$docker_command" exec --env REDISCLI_AUTH seafile-redis redis-cli ping
        } 2>/dev/null)" || fail_maintenance "Redis"
        unset REDISCLI_AUTH
        [ "$redis_result" = PONG ] || fail_maintenance "Redis"

        search_token="$(printf '%s:%s' "$INIT_SS_ADMIN_USER" "$INIT_SS_ADMIN_PASSWORD" | base64 | tr -d '\n')"
        if ! printf 'silent = true\nshow-error = false\nfail = true\nmax-time = 10\nheader = "Authorization: Basic %s"\nurl = "http://127.0.0.1:4080/api/permissions"\n' \
          "$search_token" \
          | "$docker_command" exec --interactive seafile-seasearch curl --config - >/dev/null 2>&1
        then
          fail_maintenance "SeaSearch"
        fi

        if ! "$docker_command" exec seafile-notification \
          curl --fail --silent --max-time 10 http://127.0.0.1:8083/ping >/dev/null 2>&1
        then
          fail_maintenance "Notification"
        fi
        if ! "$docker_command" exec seafile-metadata sh -ec \
          'test -r /run/seafile/seafile.conf && test -d /shared/seafile/md-data && kill -0 1' \
          >/dev/null 2>&1
        then
          fail_maintenance "Metadata"
        fi

        patterns="$(mktemp "$host_dir/.seafile-health-patterns.XXXXXX")"
        cleanup_health() {
          rm -f -- "$patterns"
        }
        trap cleanup_health EXIT HUP INT TERM
        for key in \
          INIT_SEAFILE_MYSQL_ROOT_PASSWORD SEAFILE_MYSQL_DB_PASSWORD REDIS_PASSWORD \
          JWT_PRIVATE_KEY SEAHUB_SECRET_KEY INIT_SEAFILE_ADMIN_EMAIL \
          INIT_SEAFILE_ADMIN_PASSWORD INIT_SS_ADMIN_USER INIT_SS_ADMIN_PASSWORD \
          SEAFILE_OAUTH_CLIENT_ID SEAFILE_OAUTH_CLIENT_SECRET ONLYOFFICE_JWT_SECRET
        do
          printf '%s\n' "''${!key}" >>"$patterns"
        done
        printf '%s\n' "$search_token" >>"$patterns"
        chmod 0400 "$patterns"
        unset search_token INIT_SEAFILE_MYSQL_ROOT_PASSWORD SEAFILE_MYSQL_DB_PASSWORD \
          REDIS_PASSWORD JWT_PRIVATE_KEY SEAHUB_SECRET_KEY INIT_SEAFILE_ADMIN_PASSWORD \
          INIT_SS_ADMIN_PASSWORD SEAFILE_OAUTH_CLIENT_SECRET ONLYOFFICE_JWT_SECRET

        scan_deadline="$((SECONDS + 120))"
        for log_tree in "$state_dir/shared/logs" "$state_dir/shared/seafile/logs"; do
          if [ -e "$log_tree" ] || [ -L "$log_tree" ]; then
            [ -d "$log_tree" ] && [ ! -L "$log_tree" ] || fail_maintenance "persistent log"
            entry_count="$({ timeout 30 find "$log_tree" -mindepth 1 -printf . | wc -c; } 2>/dev/null)" \
              || fail_maintenance "persistent log"
            [ "$entry_count" -le 10000 ] || fail_maintenance "persistent log"
            unsafe_count="$({ timeout 30 find "$log_tree" -mindepth 1 ! -type d ! -type f -printf . | wc -c; } 2>/dev/null)" \
              || fail_maintenance "persistent log"
            [ "$unsafe_count" -eq 0 ] || fail_maintenance "persistent log"
            oversized_count="$({ timeout 30 find "$log_tree" -type f -size +16777215c -printf . | wc -c; } 2>/dev/null)" \
              || fail_maintenance "persistent log"
            [ "$oversized_count" -eq 0 ] || fail_maintenance "persistent log"
            while IFS= read -r -d "" candidate; do
              [ "$SECONDS" -le "$scan_deadline" ] || fail_maintenance "persistent log"
              if timeout 5 grep -F -q -f "$patterns" -- "$candidate" 2>/dev/null; then
                fail_maintenance "persistent log"
              else
                grep_status="$?"
                [ "$grep_status" -eq 1 ] || fail_maintenance "persistent log"
              fi
            done < <(timeout 30 find "$log_tree" -type f -print0)
          fi
        done

        expected_owner="''${SEAFILE_EXPECTED_OWNER:-0:0}"
        config_dir="$state_dir/shared/seafile/conf"
        declare -A expected_targets=(
          [.env]="$app_dir/seafile.env"
          [seahub_settings.py]="$app_dir/seahub_settings.py"
          [seafevents.conf]="$app_dir/seafevents.conf"
          [seafile.conf]="$app_dir/seafile.conf"
          [seafdav.conf]="$app_dir/seafdav.conf"
        )
        symlink_count=0
        while IFS= read -r -d "" linked; do
          name="''${linked##*/}"
          [ "''${expected_targets[$name]+present}" = present ] || fail_maintenance "runtime configuration"
          [ "$linked" = "$config_dir/$name" ] || fail_maintenance "runtime configuration"
          [ "$(readlink "$linked")" = "''${expected_targets[$name]}" ] \
            || fail_maintenance "runtime configuration"
          [ "$(stat --format '%u:%g' -- "$linked")" = "$expected_owner" ] \
            || fail_maintenance "runtime configuration"
          symlink_count="$((symlink_count + 1))"
        done < <(find "$config_dir" -mindepth 1 -maxdepth 1 -type l -print0)
        [ "$symlink_count" -eq 5 ] || fail_maintenance "runtime configuration"
        for target in "''${expected_targets[@]}" "$metadata_dir/seafile.conf"; do
          [ -f "$target" ] && [ ! -L "$target" ] || fail_maintenance "runtime configuration"
          case "$(stat --format '%a' -- "$target")" in
            400 | 440 | 444) ;;
            *) fail_maintenance "runtime configuration" ;;
          esac
        done

        validate_state_command="''${SEAFILE_VALIDATE_STATE_COMMAND:-seafile-validate-state}"
        "$validate_state_command" >/dev/null 2>&1 || fail_maintenance "dataset"

        account_count="$({
          "$docker_command" exec --interactive seafile ${pythonCommand} <<'PY'
    from seahub.base.accounts import User
    print(User.objects.filter(is_active=True).count())
    PY
        } 2>/dev/null)" || fail_maintenance "account count"
        [[ "$account_count" =~ ^[0-9]+$ ]] || fail_maintenance "account count"
        [ "$account_count" -le ${toString cfg.licenseUserLimit} ] || fail_maintenance "account count"

        rm -f -- "$patterns"
        trap - EXIT HUP INT TERM
        echo "Seafile local health is healthy"
  '';
  metadataProbePython = ''
    import json
    import os
    import time
    import urllib.error
    import urllib.parse
    import urllib.request
    import uuid

    base = "http://127.0.0.1"
    library_name = ".seafile-health"
    original_name = ".probe-" + uuid.uuid4().hex + ".txt"
    updated_name = ".probe-" + uuid.uuid4().hex + ".txt"
    repo_id = None
    token = None

    def request(path, method="GET", body=None, query=None):
        url = base + path
        if query:
            url += "?" + urllib.parse.urlencode(query)
        data = None
        headers = {"Accept": "application/json"}
        if body is not None:
            data = urllib.parse.urlencode(body).encode()
            headers["Content-Type"] = "application/x-www-form-urlencoded"
        if token:
            headers["Authorization"] = "Token " + token
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=30) as response:
            payload = response.read()
            return json.loads(payload) if payload else None

    def safe_path(name):
        path = "/" + name
        if "/" in name or not name.startswith(".probe-") or not name.endswith(".txt"):
            raise RuntimeError("unsafe probe path")
        return path

    try:
        auth = request("/api2/auth-token/", "POST", {
            "username": os.environ["INIT_SEAFILE_ADMIN_EMAIL"],
            "password": os.environ["INIT_SEAFILE_ADMIN_PASSWORD"],
        })
        token = auth["token"]
        repos = request("/api2/repos/", query={"type": "mine"})
        matches = [repo for repo in repos if repo.get("name") == library_name]
        if len(matches) > 1:
            raise RuntimeError("ambiguous health library")
        if matches:
            repo = matches[0]
        else:
            repo = request("/api2/repos/", "POST", {"name": library_name})
        repo_id = repo.get("id") or repo.get("repo_id")
        owner = repo.get("owner") or repo.get("owner_email")
        if not repo_id or (owner and owner.casefold() != os.environ["INIT_SEAFILE_ADMIN_EMAIL"].casefold()):
            raise RuntimeError("unowned health library")
        verified = request("/api2/repos/" + repo_id + "/")
        verified_id = verified.get("id") or verified.get("repo_id")
        if verified_id != repo_id:
            raise RuntimeError("library resolution escaped")

        request("/api/v2.1/repos/" + repo_id + "/metadata/", "PUT", {})
        request("/api/v2.1/repos/" + repo_id + "/file/", "POST", {"operation": "create"}, {"p": safe_path(original_name)})

        deadline = time.monotonic() + 120
        while True:
            status = request("/api/v2.1/repos/" + repo_id + "/metadata/")
            if status and any(status.get(key) is True for key in ("enabled", "is_enabled", "metadata_enabled")):
                break
            if time.monotonic() >= deadline:
                raise RuntimeError("metadata enablement timed out")
            time.sleep(2)

        request("/api/v2.1/repos/" + repo_id + "/metadata/record/", "PUT", {
            "parent_dir": "/",
            "file_name": original_name,
            "data": json.dumps({"Name": updated_name}),
        })
        detail = request("/api2/repos/" + repo_id + "/file/detail/", query={"p": safe_path(updated_name)})
        if detail.get("name") != updated_name:
            raise RuntimeError("metadata property round trip failed")
        request("/api/v2.1/repos/" + repo_id + "/file/", "DELETE", query={"p": safe_path(updated_name)})
    except Exception:
        if token and repo_id:
            for name in (original_name, updated_name):
                try:
                    request("/api/v2.1/repos/" + repo_id + "/file/", "DELETE", query={"p": safe_path(name)})
                except Exception:
                    pass
        raise SystemExit(1)
  '';
  metadataProbeProgram = pkgs.writeText "seafile-metadata-probe.py" metadataProbePython;
  heavyPrelude = ''
    ${commandPrelude}
    if [ "$("$id_command" -u)" -ne 0 ]; then
      echo "This Seafile maintenance command must run as root" >&2
      exit 77
    fi
    exec 9>"$lock_file"
    if ! "$flock_command" -w 1800 9; then
      echo "Seafile maintenance lock timed out" >&2
      exit 75
    fi
  '';
  requireActiveStack = ''
    if ! "$systemctl_command" is-active --quiet seafile-compose.service; then
      echo "Seafile Compose service is not active" >&2
      exit 69
    fi
  '';
  metadataProbeScript = ''
    ${heavyPrelude}
    ${requireActiveStack}
    load_runtime_environment
    if ! "$docker_command" exec --interactive \
      --env INIT_SEAFILE_ADMIN_EMAIL --env INIT_SEAFILE_ADMIN_PASSWORD \
      seafile ${pythonCommand} <${metadataProbeProgram} >/dev/null 2>&1
    then
      fail_maintenance "Metadata functional"
    fi
    unset INIT_SEAFILE_ADMIN_EMAIL INIT_SEAFILE_ADMIN_PASSWORD
    echo "Seafile Metadata functional probe passed"
  '';
  notificationPublicCheckScript = ''
    ${heavyPrelude}
    ${requireActiveStack}
    marker="$state_dir/control/public-ingress-accepted"
    [ -f "$marker" ] && [ ! -L "$marker" ] \
      || { echo "public ingress acceptance pending"; exit 0; }
    [ "$(stat --format '%u:%g:%a' -- "$marker")" = 0:0:600 ] \
      || fail_maintenance "public ingress marker"
    "$curl_command" --fail --silent --show-error --max-time 15 \
      ${lib.escapeShellArg "${cfg.publicUrl}/notification/ping"} >/dev/null \
      || fail_maintenance "public Notification"
    websocket_status="$({
      "$curl_command" --silent --show-error --max-time 15 --output /dev/null \
        --write-out '%{http_code}' \
        --header 'Connection: Upgrade' \
        --header 'Upgrade: websocket' \
        --header 'Sec-WebSocket-Version: 13' \
            --header 'Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==' \
        ${lib.escapeShellArg "${cfg.publicUrl}/notification/"}
    } 2>/dev/null)" || fail_maintenance "public Notification WebSocket"
    [ "$websocket_status" = 101 ] || fail_maintenance "public Notification WebSocket"
    echo "Seafile public Notification probe passed"
  '';
  onlyOfficeProbePython = ''
    import io
    import json
    import os
    import threading
    import time
    import urllib.parse
    import urllib.request
    import uuid
    import zipfile
    from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

    base = "http://127.0.0.1"
    library_name = ".seafile-health"
    file_name = ".probe-" + uuid.uuid4().hex + ".docx"
    file_path = "/" + file_name
    repo_id = None
    token = None

    def api(path, method="GET", body=None, query=None, raw=False):
        url = base + path
        if query:
            url += "?" + urllib.parse.urlencode(query)
        data = None
        headers = {"Accept": "application/json"}
        if body is not None:
            data = urllib.parse.urlencode(body).encode()
            headers["Content-Type"] = "application/x-www-form-urlencoded"
        if token:
            headers["Authorization"] = "Token " + token
        request = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = response.read()
            if raw:
                return payload
            return json.loads(payload) if payload else None

    def make_document():
        stream = io.BytesIO()
        with zipfile.ZipFile(stream, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("[Content_Types].xml", """<?xml version="1.0" encoding="UTF-8"?>
    <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
      <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
      <Default Extension="xml" ContentType="application/xml"/>
      <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
    </Types>""")
            archive.writestr("_rels/.rels", """<?xml version="1.0" encoding="UTF-8"?>
    <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
      <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
    </Relationships>""")
            archive.writestr("word/document.xml", """<?xml version="1.0" encoding="UTF-8"?>
    <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>health</w:t></w:r></w:p></w:body></w:document>""")
        return stream.getvalue()

    def upload(content):
        upload_url = api("/api2/repos/" + repo_id + "/upload-link/")
        boundary = "seafile-health-" + uuid.uuid4().hex
        body = b"".join((
            ("--" + boundary + "\r\nContent-Disposition: form-data; name=\"parent_dir\"\r\n\r\n/\r\n").encode(),
            ("--" + boundary + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\"" + file_name + "\"\r\n"
             "Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document\r\n\r\n").encode(),
            content,
            ("\r\n--" + boundary + "--\r\n").encode(),
        ))
        headers = {"Authorization": "Token " + token, "Content-Type": "multipart/form-data; boundary=" + boundary}
        with urllib.request.urlopen(urllib.request.Request(upload_url, body, headers, method="POST"), timeout=60) as response:
            response.read()

    try:
        auth = api("/api2/auth-token/", "POST", {
            "username": os.environ["INIT_SEAFILE_ADMIN_EMAIL"],
            "password": os.environ["INIT_SEAFILE_ADMIN_PASSWORD"],
        })
        token = auth["token"]
        repos = api("/api2/repos/", query={"type": "mine"})
        matches = [repo for repo in repos if repo.get("name") == library_name]
        if len(matches) > 1:
            raise RuntimeError("health library is not uniquely resolved")
        if matches:
            repo = matches[0]
        else:
            repo = api("/api2/repos/", "POST", {"name": library_name})
        repo_id = repo.get("id") or repo.get("repo_id")
        owner = repo.get("owner") or repo.get("owner_email")
        if not repo_id or (owner and owner.casefold() != os.environ["INIT_SEAFILE_ADMIN_EMAIL"].casefold()):
            raise RuntimeError("health library ownership mismatch")

        upload(make_document())
        before = api("/api2/repos/" + repo_id + "/file/detail/", query={"p": file_path})
        before_id = before.get("id")
        if not before_id:
            raise RuntimeError("probe document was not created")

        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "seahub.settings")
        import django
        django.setup()
        from django.test import RequestFactory
        from seahub.base.accounts import User
        from seahub.onlyoffice.converter import get_converter_uri
        from seahub.onlyoffice.utils import get_onlyoffice_dict

        username = os.environ["INIT_SEAFILE_ADMIN_EMAIL"]
        request = RequestFactory().get("/", HTTP_HOST="127.0.0.1")
        request.user = User.objects.get(email=username)
        editor = get_onlyoffice_dict(request, username, repo_id, file_path)
        doc_key = editor.get("doc_key")
        doc_url = editor.get("doc_url")
        if not doc_key or not doc_url:
            raise RuntimeError("OnlyOffice editor session was not created")
        odt_url = get_converter_uri(doc_url, "docx", "odt", doc_key + "-odt", False, None)
        converted_url = get_converter_uri(odt_url, "odt", "docx", doc_key + "-docx", False, None)
        if not converted_url:
            raise RuntimeError("OnlyOffice conversion did not complete")
        with urllib.request.urlopen(converted_url, timeout=60) as response:
            converted = response.read(16777217)
        if not converted.startswith(b"PK") or len(converted) > 16777216:
            raise RuntimeError("OnlyOffice returned an invalid bounded document")

        class ContentHandler(BaseHTTPRequestHandler):
            def do_GET(self):
                if self.path != "/document":
                    self.send_error(404)
                    return
                self.send_response(200)
                self.send_header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
                self.send_header("Content-Length", str(len(converted)))
                self.end_headers()
                self.wfile.write(converted)
            def log_message(self, _format, *args):
                pass

        server = ThreadingHTTPServer(("127.0.0.1", 0), ContentHandler)
        worker = threading.Thread(target=server.serve_forever, daemon=True)
        worker.start()
        callback = json.dumps({
            "key": doc_key,
            "status": 2,
            "url": "http://127.0.0.1:" + str(server.server_port) + "/document",
            "users": [username],
        }).encode()
        callback_request = urllib.request.Request(
            base + "/onlyoffice/editor-callback/", callback,
            {"Content-Type": "application/json"}, method="POST")
        try:
            with urllib.request.urlopen(callback_request, timeout=60) as response:
                callback_result = json.loads(response.read())
        finally:
            server.shutdown()
            server.server_close()
        if callback_result.get("error") != 0:
            raise RuntimeError("OnlyOffice callback was rejected")

        deadline = time.monotonic() + 120
        while True:
            after = api("/api2/repos/" + repo_id + "/file/detail/", query={"p": file_path})
            if after.get("id") and after.get("id") != before_id:
                reopened = api("/api2/repos/" + repo_id + "/file/", query={"p": file_path}, raw=True)
                if not reopened.startswith(b"PK"):
                    raise RuntimeError("callback result could not be reopened")
                break
            if time.monotonic() >= deadline:
                raise RuntimeError("OnlyOffice callback did not create a revision")
            time.sleep(2)
    except Exception:
        raise SystemExit(1) from None
    finally:
        if token and repo_id:
            try:
                api("/api/v2.1/repos/" + repo_id + "/file/", "DELETE", query={"p": file_path})
            except Exception:
                raise SystemExit(1) from None
  '';
  onlyOfficeProbeProgram = pkgs.writeText "seafile-onlyoffice-smoke-test.py" onlyOfficeProbePython;
  onlyOfficeSmokeTestScript = ''
          ${heavyPrelude}
          ${requireActiveStack}
    marker="$state_dir/control/public-ingress-accepted"
    [ -f "$marker" ] && [ ! -L "$marker" ] \
      || { echo "public ingress acceptance pending"; exit 0; }
          load_runtime_environment
          probe_program="''${SEAFILE_ONLYOFFICE_PROBE_PROGRAM:-${onlyOfficeProbeProgram}}"
          [ -f "$probe_program" ] && [ ! -L "$probe_program" ] \
            || fail_maintenance "OnlyOffice functional"
          if ! "$docker_command" exec --interactive \
            --env INIT_SEAFILE_ADMIN_EMAIL --env INIT_SEAFILE_ADMIN_PASSWORD \
            seafile ${pythonCommand} <"$probe_program" >/dev/null 2>&1
    then
      fail_maintenance "OnlyOffice functional"
    fi
    unset INIT_SEAFILE_ADMIN_EMAIL INIT_SEAFILE_ADMIN_PASSWORD
    echo "Seafile OnlyOffice callback and reopen probe passed"
  '';
  enablePublicHealthScript = ''
    state_dir="''${SEAFILE_STATE_DIR:-${cfg.stateDir}}"
    id_command="''${SEAFILE_ID_COMMAND:-id}"
    if [ "$("$id_command" -u)" -ne 0 ]; then
      echo "This Seafile control command must run as root" >&2
      exit 77
    fi
    control_dir="$state_dir/control"
    [ -d "$control_dir" ] && [ ! -L "$control_dir" ] \
      || { echo "Seafile control directory is invalid" >&2; exit 65; }
    [ "$(stat --format '%u:%g:%a' -- "$control_dir")" = 0:0:700 ] \
      || { echo "Seafile control directory is unsafe" >&2; exit 65; }
    marker="$control_dir/public-ingress-accepted"
    if [ -e "$marker" ] || [ -L "$marker" ]; then
      [ -f "$marker" ] && [ ! -L "$marker" ] \
        && [ "$(stat --format '%u:%g:%a' -- "$marker")" = 0:0:600 ] \
        || { echo "Seafile public health marker is unsafe" >&2; exit 65; }
      exit 0
    fi
    temporary="$(mktemp "$control_dir/.public-ingress-accepted.XXXXXX")"
    trap 'rm -f -- "$temporary"' EXIT HUP INT TERM
    chmod 0600 "$temporary"
    chown 0:0 "$temporary"
    printf '%s\n' 'v1 accepted' >"$temporary"
    mv -T -- "$temporary" "$marker"
    trap - EXIT HUP INT TERM
    echo "Seafile public health probes enabled"
  '';
  extendedHealthScript = ''
    ${heavyPrelude}
    health_command="''${SEAFILE_HEALTH_COMMAND:-seafile-health-check}"
    metadata_probe_command="''${SEAFILE_METADATA_PROBE_COMMAND:-seafile-metadata-probe}"
    notification_probe_command="''${SEAFILE_NOTIFICATION_PROBE_COMMAND:-seafile-notification-public-check}"
    onlyoffice_probe_command="''${SEAFILE_ONLYOFFICE_PROBE_COMMAND:-seafile-onlyoffice-smoke-test}"
    journalctl_command="''${SEAFILE_JOURNALCTL_COMMAND:-journalctl}"

    SEAFILE_MAINTENANCE_LOCK_HELD=1 "$health_command" >/dev/null \
      || fail_maintenance "local health"

          marker="$state_dir/control/last-validated-backup"
          [ -f "$marker" ] && [ ! -L "$marker" ] \
            || fail_maintenance "backup freshness"
          expected_control_owner="''${SEAFILE_EXPECTED_CONTROL_OWNER:-0:0}"
          [ "$(stat --format '%u:%g:%a' -- "$marker")" = "$expected_control_owner:600" ] \
            || fail_maintenance "backup freshness"
    set_name="$(jq --raw-output '.set // empty' "$marker")" \
      || fail_maintenance "backup freshness"
    validated_at="$(jq --raw-output '.validated_at_epoch // empty' "$marker")" \
      || fail_maintenance "backup freshness"
    writers_quiesced="$(jq --raw-output '.writers_quiesced // false' "$marker")" \
      || fail_maintenance "backup freshness"
    [[ "$set_name" =~ ^seafile-[0-9]{8}T[0-9]{6}\.[0-9]{9}Z$ ]] \
      || fail_maintenance "backup freshness"
    [[ "$validated_at" =~ ^[0-9]+$ ]] || fail_maintenance "backup freshness"
    [ "$writers_quiesced" = true ] || fail_maintenance "backup freshness"
    manifest="$state_dir/backups/$set_name/manifest.json"
    [ -f "$manifest" ] && [ ! -L "$manifest" ] \
      || fail_maintenance "backup freshness"
    jq --exit-status '.writers_quiesced == true' "$manifest" >/dev/null \
      || fail_maintenance "backup freshness"
    now="$(date --utc +%s)"
    age="$((now - validated_at))"
          [ "$age" -ge 0 ] && [ "$age" -le 129600 ] \
            || fail_maintenance "backup freshness"
          [ "$("$systemctl_command" show --property Result --value borgmatic.service)" = success ] \
            || fail_maintenance "backup freshness"
          completion_records="$(mktemp "$host_dir/.seafile-borg-completion.XXXXXX")"
          trap 'rm -f -- "$completion_records"' EXIT HUP INT TERM
          timeout 30 "$journalctl_command" --unit borgmatic.service --since '@'"$validated_at" \
            --output=json --no-pager --quiet >"$completion_records" 2>/dev/null \
            || fail_maintenance "backup freshness"
          minimum_completion_usec="$((validated_at * 1000000))"
          jq --slurp --exit-status --argjson minimum "$minimum_completion_usec" '
            any(.[];
              .MESSAGE_ID == "39f53479d3a045ac8e11786248231fbf"
              and .UNIT == "borgmatic.service"
              and ((.__REALTIME_TIMESTAMP | tonumber) >= $minimum))
          ' "$completion_records" >/dev/null \
            || fail_maintenance "backup freshness"
          rm -f -- "$completion_records"
          trap - EXIT HUP INT TERM

          metadata_log="$(mktemp "$host_dir/.seafile-metadata-log.XXXXXX")"
    trap 'rm -f -- "$metadata_log"' EXIT HUP INT TERM
    "$docker_command" logs --since 25h seafile-metadata >"$metadata_log" 2>&1 \
      || fail_maintenance "Metadata startup"
    grep -F -q 'Starting Metadata server' "$metadata_log" \
      || fail_maintenance "Metadata startup"
    rm -f -- "$metadata_log"
    trap - EXIT HUP INT TERM

    # Release the lock before calling independently lock-scoped functional jobs.
    exec 9>&-
    "$metadata_probe_command" >/dev/null || fail_maintenance "Metadata functional"

    public_marker="$state_dir/control/public-ingress-accepted"
    if [ ! -e "$public_marker" ] && [ ! -L "$public_marker" ]; then
      echo "public ingress acceptance pending"
      exit 0
    fi
    "$notification_probe_command" >/dev/null || fail_maintenance "public Notification"
    "$onlyoffice_probe_command" >/dev/null || fail_maintenance "OnlyOffice functional"
    echo "Seafile extended health is healthy"
  '';
  quietMaintenance = name: command: success: ''
    ${heavyPrelude}
    ${requireActiveStack}
    report="$(mktemp "$host_dir/.${name}.XXXXXX")"
    trap 'rm -f -- "$report"' EXIT HUP INT TERM
    if ! timeout 86400 "$docker_command" exec seafile sh -ec ${lib.escapeShellArg command} \
      >"$report" 2>&1
    then
      echo "Seafile ${name} failed" >&2
      exit 69
    fi
    rm -f -- "$report"
    trap - EXIT HUP INT TERM
    echo ${lib.escapeShellArg success}
  '';
  fsckShallowScript = quietMaintenance "shallow fsck" ''
    cd /opt/seafile/seafile-server-latest
    exec ./seaf-fsck.sh --shallow
  '' "Seafile shallow read-only fsck passed";
  fsckFullScript = quietMaintenance "full fsck" ''
    cd /opt/seafile/seafile-server-latest
    exec ./seaf-fsck.sh
  '' "Seafile full read-only fsck passed";
  gcDryRunScript = quietMaintenance "GC dry run" ''
    cd /opt/seafile/seafile-server-latest
    exec ./seaf-gc.sh --dry-run
  '' "Seafile GC dry run passed";
  searchStatusScript = ''
    ${heavyPrelude}
    ${requireActiveStack}
    load_runtime_environment
    search_token="$(printf '%s:%s' "$INIT_SS_ADMIN_USER" "$INIT_SS_ADMIN_PASSWORD" | base64 | tr -d '\n')"
    if ! printf 'silent = true\nshow-error = false\nfail = true\nmax-time = 30\nheader = "Authorization: Basic %s"\nurl = "http://127.0.0.1:4080/api/permissions"\n' \
      "$search_token" | "$docker_command" exec --interactive seafile-seasearch curl --config - \
      >/dev/null 2>&1
    then
      fail_maintenance "SeaSearch"
    fi
    unset search_token INIT_SS_ADMIN_USER INIT_SS_ADMIN_PASSWORD
    echo "Seafile SeaSearch authenticated status passed"
  '';
  searchUpdateScript = quietMaintenance "SeaSearch update" ''
    cd /opt/seafile/seafile-server-latest
    exec ./pro/pro.py search --update
  '' "Seafile SeaSearch update completed";
  searchRebuildScript = ''
    ${heavyPrelude}
    ${requireActiveStack}
    echo "WARNING: rebuilding derived Seafile search state; file service remains available" >&2
    report="$(mktemp "$host_dir/.seafile-search-rebuild.XXXXXX")"
    trap 'rm -f -- "$report"' EXIT HUP INT TERM
    if ! timeout 86400 "$docker_command" exec seafile sh -ec '
      cd /opt/seafile/seafile-server-latest
      ./pro/pro.py search --clear
      exec ./pro/pro.py search --update
    ' >"$report" 2>&1
    then
      echo "Seafile SeaSearch rebuild failed" >&2
      exit 69
    fi
    rm -f -- "$report"
    trap - EXIT HUP INT TERM
    echo "Seafile derived SeaSearch state rebuilt"
  '';
  healthCheck = pkgs.writeShellApplication {
    name = "seafile-health-check";
    runtimeInputs = [
      cfg.validateStatePackage
      config.virtualisation.docker.package
      pkgs.bash
      pkgs.coreutils
      pkgs.curl
      pkgs.findutils
      pkgs.gnugrep
      pkgs.systemd
      pkgs.util-linux
    ];
    text = healthCheckScript;
  };
  mkMaintenancePackage =
    name: text: extraInputs:
    pkgs.writeShellApplication {
      inherit name text;
      runtimeInputs = [
        config.virtualisation.docker.package
        pkgs.bash
        pkgs.coreutils
        pkgs.curl
        pkgs.systemd
        pkgs.util-linux
      ]
      ++ extraInputs;
    };
  metadataProbe = mkMaintenancePackage "seafile-metadata-probe" metadataProbeScript [ ];
  notificationPublicCheck =
    mkMaintenancePackage "seafile-notification-public-check" notificationPublicCheckScript
      [ ];
  onlyOfficeSmokeTest =
    mkMaintenancePackage "seafile-onlyoffice-smoke-test" onlyOfficeSmokeTestScript
      [ ];
  enablePublicHealth = pkgs.writeShellApplication {
    name = "seafile-enable-public-health";
    runtimeInputs = [ pkgs.coreutils ];
    text = enablePublicHealthScript;
  };
  extendedHealth = mkMaintenancePackage "seafile-extended-health" extendedHealthScript [
    healthCheck
    metadataProbe
    notificationPublicCheck
    onlyOfficeSmokeTest
    pkgs.gnugrep
    pkgs.jq
  ];
  fsckShallow = mkMaintenancePackage "seafile-fsck-shallow" fsckShallowScript [ ];
  fsckFull = mkMaintenancePackage "seafile-fsck-full" fsckFullScript [ ];
  gcDryRun = mkMaintenancePackage "seafile-gc-dry-run" gcDryRunScript [ ];
  searchStatus = mkMaintenancePackage "seafile-search-status" searchStatusScript [ ];
  searchUpdate = mkMaintenancePackage "seafile-search-update" searchUpdateScript [ ];
  searchRebuild = mkMaintenancePackage "seafile-search-rebuild" searchRebuildScript [ ];
  maintenanceContractText = lib.concatStringsSep "\n" [
    healthCheckScript
    extendedHealthScript
    metadataProbeScript
    metadataProbePython
    notificationPublicCheckScript
    onlyOfficeSmokeTestScript
    onlyOfficeProbePython
    enablePublicHealthScript
    fsckShallowScript
    fsckFullScript
    gcDryRunScript
    searchStatusScript
    searchUpdateScript
    searchRebuildScript
  ];
  baseUnit = {
    after = [
      "seafile-compose.service"
      "seafile-config.service"
      "seafile-state.service"
      "docker.service"
    ];
    requires = [
      "seafile-config.service"
      "seafile-state.service"
      "docker.service"
    ];
    unitConfig.RequiresMountsFor = cfg.stateDir;
    serviceConfig = {
      Type = "oneshot";
      UMask = "0077";
    };
  };
  timedService =
    description: package: timeout:
    lib.recursiveUpdate baseUnit {
      inherit description;
      serviceConfig = {
        ExecStart = lib.getExe package;
        TimeoutStartSec = timeout;
      };
    };
  persistentTimer = description: timerConfig: {
    inherit description timerConfig;
    wantedBy = [ "timers.target" ];
  };
in
{
  options.shulker.system.modules.seafile = {
    maintenanceContractText = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Non-secret Seafile health and maintenance source for executable contracts.";
    };
    healthCheckScript = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Seafile local health source with an inherited-lock entry point.";
    };
    extendedHealthScript = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Seafile extended health source exposed for fixtures.";
    };
    metadataProbeScript = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Seafile Metadata functional probe source exposed for fixtures.";
    };
    enablePublicHealthScript = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Seafile public-health marker source exposed for fixtures.";
    };
    onlyOfficeProbePython = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Seafile OnlyOffice functional driver exposed for fixtures.";
    };
    onlyOfficeSmokeTestScript = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      internal = true;
      description = "Seafile OnlyOffice smoke-test source exposed for fixtures.";
    };
  };

  config = lib.mkIf cfg.enable {
    shulker.system.modules.seafile = {
      inherit
        enablePublicHealthScript
        extendedHealthScript
        healthCheckScript
        maintenanceContractText
        metadataProbeScript
        onlyOfficeProbePython
        onlyOfficeSmokeTestScript
        ;
    };

    environment.systemPackages = [
      healthCheck
      extendedHealth
      metadataProbe
      notificationPublicCheck
      onlyOfficeSmokeTest
      enablePublicHealth
      fsckShallow
      fsckFull
      gcDryRun
      searchStatus
      searchUpdate
      searchRebuild
    ];

    systemd.services = {
      seafile-health-check = timedService "Check local Seafile health" healthCheck 300;
      seafile-extended-health = timedService "Check extended Seafile health" extendedHealth 3600;
      seafile-metadata-probe =
        timedService "Run a bounded Seafile Metadata property probe" metadataProbe
          600;
      seafile-notification-public-check =
        timedService "Check public Seafile Notification ingress" notificationPublicCheck
          300;
      seafile-onlyoffice-smoke-test =
        timedService "Run an on-demand Seafile OnlyOffice smoke test" onlyOfficeSmokeTest
          900;
      seafile-fsck-shallow = timedService "Run read-only shallow Seafile fsck" fsckShallow 21600;
      seafile-fsck-full = timedService "Run read-only full Seafile fsck" fsckFull 86400;
      seafile-gc-dry-run = timedService "Report Seafile garbage without deleting it" gcDryRun 21600;
      seafile-search-status =
        timedService "Check authenticated Seafile SeaSearch status" searchStatus
          300;
      seafile-search-update = timedService "Update derived Seafile search state" searchUpdate 21600;
      seafile-search-rebuild = timedService "Rebuild derived Seafile search state" searchRebuild 86400;
    };

    systemd.timers = {
      seafile-health-check = persistentTimer "Check local Seafile health every fifteen minutes" {
        OnBootSec = "15m";
        OnUnitActiveSec = "15m";
        Persistent = true;
        RandomizedDelaySec = "2m";
      };
      seafile-extended-health = persistentTimer "Check extended Seafile health daily" {
        OnCalendar = "daily";
        Persistent = true;
        RandomizedDelaySec = "1h";
      };
      seafile-fsck-shallow = persistentTimer "Run shallow Seafile fsck weekly" {
        OnCalendar = "weekly";
        Persistent = true;
        RandomizedDelaySec = "6h";
      };
      seafile-fsck-full = persistentTimer "Run full Seafile fsck monthly" {
        OnCalendar = "monthly";
        Persistent = true;
        RandomizedDelaySec = "1d";
      };
      seafile-gc-dry-run = persistentTimer "Run Seafile GC dry-run weekly" {
        OnCalendar = "weekly";
        Persistent = true;
        RandomizedDelaySec = "6h";
      };
    };
  };
}
